service_name: travis-pro
repo_token: Al6rGCTqjmwTEKPLgfHQAV3ij8BxpAMxa

language: python
python:
#  - "3.2"
  - "2.7"
# command to install dependencies
install:
  #- "pip install -r requirements.txt --use-mirrors"
  - pip install coveralls
# command to run tests
script: 
  #nosetests
  nosetests --with-coverage --cover-package=saw
after_success:
  coveralls
